Add suggestions for our development principles
okgrow/guides pull request #29
Opened 2017-05-10 20:12 UTC by rgould

2017-05-10 20:51 UTC, pauldowman requested changes
One small comment, but otherwise 👍 !

2017-05-10 20:51 UTC, pauldowman commented on processes/development/README.md
> +- **Quality is the most important thing. Above all else.** This means taking time to do things correctly, and prioritizing bugs and errors above all else.
Missing new-line?

2017-05-10 23:49 UTC, rgould commented on processes/development/README.md
> +- **Quality is the most important thing. Above all else.** This means taking time to do things correctly, and prioritizing bugs and errors above all else.
I put it on the same line since i thought it was related. I could put it on the next line and indent it though. I don't really care :)

2017-05-11 00:13 UTC, pauldowman commented on processes/development/README.md
> +- **Quality is the most important thing. Above all else.** This means taking time to do things correctly, and prioritizing bugs and errors above all else.
OK, sure then.

2017-10-12 18:19 UTC, cfnelson approved these changes
👍 
Looks like Paul agreed with your response Richard.  Going to merge as it's been sitting here for awhile! 💃

2017-10-12 18:20 UTC, merged